#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ABP_Reverse_Bow { struct FAnimBlueprintGeneratedConstantData; }

namespace Altar { enum class EPixelFormat : uint32; }

namespace TABP_Recoil_Multiple { struct FAnimBlueprintGeneratedConstantData; }

namespace TABP_Stagger_Swim { struct FAnimBlueprintGeneratedConstantData; }

namespace TABP_Dodge { struct FAnimBlueprintGeneratedConstantData; }

namespace CoreUObject { enum class EPixelFormat : uint8; }

namespace TABP_FeetIK_Humanoid { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Reverse_ThirdPerson_Humanoid { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_Reverse_FirstPerson_Humanoid { struct FAnimBlueprintGeneratedConstantData; }

namespace TABP_Stagger { struct FAnimBlueprintGeneratedConstantData; }

namespace TABP_Resurrection { struct FAnimBlueprintGeneratedConstantData; }


namespace TABP_MeleeAttack_LightCombo
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_HorseRiding_InAir
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_SpellCast_Single
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_EnhancedLocomotionSneaking
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_TorchLayer_ThirdPerson
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_LocomotionSwimming
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_EquipUnequip_StandSneak_Single
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_TorchLayer_FirstPerson
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ABP_HeadPostProcess
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_HitReact
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_LookAt
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace CR_Neck
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace TABP_HumanoidLowerAndUpperBody
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace CR_FeetK_Humanoid
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace TABP_TurnInPlaceFP
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_Horse_Locomotion_Swimming
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_EnhancedLocomotionInAir
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_SpecialIdleAndDock
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_BlockShield
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_GetUp
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_EnhancedLocomotionStanding
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_EquipUnequip_StandSneakSwim_Single
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_StandSneak_StaffAttack
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_ReverseCharacter
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_HumanoidHead
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_HorseJump
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_HumanoidTailPhysics
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_Blink_Humanoid
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_ShieldHandPose
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_ConversationIdle
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_Reverse_Bow_Generic
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_AimOffset
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_HorseRiding_Ground
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_MeleeAttack_HeavyCombo
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_PoseSnapshot
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_MeleeAttack_MediumCombo
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_TurnInPlace
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_HorseRiding_Swimming
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_LocomotionStanding
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace TABP_StandSneak_BowAttack
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_Horse_Locomotion
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_EnhancedLocomotionSystem
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ABP_InventoryCharacter
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace TABP_LocomotionSneaking
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
